version: '3.4'

services:
  api:
    image: zekiunal/foreweather-api
    ports:
      - "8888:80"
    environment:
      DB_HOST: 'mysql'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'Fore@123'
      DB_NAME: 'foreweather'
    networks:
      - syslog
    volumes:
      - db_data:/var/lib/mysql
  publisher:
    image: zekiunal/foreweather-publisher
    environment:
      QUEUE_HOST: 'beanstalk'
      OAUTH_CLIENT_ID: 'notify'
      OAUTH_CLIENT_SECRET: 'teknasyon'
      OAUTH_TOKEN_URL: 'http://api/oauth2/token'
      OAUTH_CLIENT_REDIRECT_URL: ''
      OAUTH_CLIENT_AUTHORIZE_URL: 'http://api/oauth2/authorize'
      OAUTH_OWNER_DETAILS: 'http://api/oauth2/me'
      API_BASE_URL: 'http://api'
      NOTIFY_HOUR: '19:10'
    networks:
      - syslog
  notify:
    image: zekiunal/foreweather-notify
    environment:
      QUEUE_HOST: 'beanstalk'
      OAUTH_CLIENT_ID: 'notify'
      OAUTH_CLIENT_SECRET: 'teknasyon'
      OAUTH_TOKEN_URL: 'http://api/oauth2/token'
      OAUTH_CLIENT_REDIRECT_URL: ''
      OAUTH_CLIENT_AUTHORIZE_URL: 'http://api/oauth2/authorize'
      OAUTH_OWNER_DETAILS: 'http://api/oauth2/me'
      API_BASE_URL: 'http://api'
    networks:
      - syslog
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'foreweather'
      MYSQL_ROOT_PASSWORD: 'Fore@123'
    networks:
      - syslog
  beanstalk:
    image: uretgec/beanstalkd-alpine:latest
    networks:
      - syslog
  bconsole:
    image: ohmcoe/beanstalk_console:latest
    ports:
      - "8044:80"
    environment:
      APACHE_PORT: '80'
      BEANSTALKD_HOST: 'beanstalk'
      BEANSTALKD_PORT: '11300'
    networks:
      - syslog
  syslog:
    image: zekiunal/syslog
    labels:
      com.monitoring.group: "logging"
    ports:
      - 5514:5514/udp
    networks:
      - syslog
    volumes:
      - ./docker/rsyslog/rsyslog.conf:/etc/rsyslog.conf
  logstash:
    image: zekiunal/logstash
    ports:
      - 5044:5044/udp
    networks:
      - syslog
    volumes:
      - ./docker/logstash:/conf
    command: logstash -f /conf/logstash.conf

  logspout:
    image: gliderlabs/logspout:v3.2.1
    networks:
      - syslog
    deploy:
      mode: global
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: syslog://syslog:514
    environment:
      SYSLOG_FORMAT: 'rfc3164'
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - syslog
networks:
  syslog:

volumes:
  db_data: {}
