version: '3.4'

services:
  api:
    image: zekiunal/foreweather-api
    ports:
      - "8888:80"
    environment:
      DB_HOST: 'mysql'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'Fore@123'
      DB_NAME: 'foreweather'
  publisher:
    image: zekiunal/foreweather-publisher
    environment:
      QUEUE_HOST: 'beanstalk'
      OAUTH_CLIENT_ID: 'notify'
      OAUTH_CLIENT_SECRET: 'teknasyon'
      OAUTH_TOKEN_URL: 'http://api/oauth2/token'
      OAUTH_CLIENT_REDIRECT_URL: ''
      OAUTH_CLIENT_AUTHORIZE_URL: 'http://api/oauth2/authorize'
      OAUTH_OWNER_DETAILS: 'http://api/oauth2/me'
      API_BASE_URL: 'http://api'
      NOTIFY_HOUR: '19:10'
  notify:
    image: zekiunal/foreweather-notify
    environment:
      QUEUE_HOST: 'beanstalk'
      OAUTH_CLIENT_ID: 'notify'
      OAUTH_CLIENT_SECRET: 'teknasyon'
      OAUTH_TOKEN_URL: 'http://api/oauth2/token'
      OAUTH_CLIENT_REDIRECT_URL: ''
      OAUTH_CLIENT_AUTHORIZE_URL: 'http://api/oauth2/authorize'
      OAUTH_OWNER_DETAILS: 'http://api/oauth2/me'
      API_BASE_URL: 'http://api'

  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'foreweather'
      MYSQL_ROOT_PASSWORD: 'Fore@123'

  beanstalk:
    image: uretgec/beanstalkd-alpine:latest

  bconsole:
    image: ohmcoe/beanstalk_console:latest
    ports:
      - "8044:80"
    environment:
      APACHE_PORT: '80'
      BEANSTALKD_HOST: 'beanstalk'
      BEANSTALKD_PORT: '11300'
