version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: zekiunal/foreweather-api
    ports:
      - "8888:80"
      - "4422:22"
    links:
      - mysql
    environment:
      DB_ADAPTER: 'mysql'
      DB_HOST: 'mysql'
      DB_PORT: '3306'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'Fore@123'
      DB_NAME: 'foreweather'
  mysql:
    image: mysql:5.6
    ports:
      - "3333:3306"
    restart: always
    environment:
      MYSQL_DATABASE: 'foreweather'
      MYSQL_ROOT_PASSWORD: 'Fore@123'
